name: shoe_visual_customizer_mobile
description: Flutter scanner MVP for Shoe Visual Customizer.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  cookie_jar: ^4.0.8
  cross_file: ^0.3.4+2
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  model_viewer_plus: ^1.10.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
